'use server'

import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'
import { supabaseServer, createOrder, updateOrderStatus } from '@/lib/supabase/server'
import { uploadPaymentProof } from '@/lib/supabase/server'
import {
  sendOrderConfirmationEmail,
  sendPaymentSubmittedEmail,
  sendAdminNotificationNewOrder,
} from '@/lib/email'

export async function createNewOrder(
  userId: string,
  botId: string,
  botName: string,
  botPrice: number,
  paymentMethod: string,
  transactionId: string,
  customerEmail: string,
  customerName: string
) {
  try {
    // Create order in database
    const orderData = await createOrder(
      userId,
      botId,
      botName,
      botPrice,
      paymentMethod,
      transactionId
    )

    // createOrder now uses .select().single(), so this is the created row
    // itself - not an array, and never null on success.
    if (!orderData?.id) {
      throw new Error('The order was not returned after creation, so its id is unavailable.')
    }

    const order = orderData

    // Send confirmation email to customer
    try {
      await sendOrderConfirmationEmail(customerEmail, customerName, order.id, botName, botPrice, paymentMethod)
    } catch (emailError) {
      console.error('Failed to send order confirmation email:', emailError)
      // Don't fail the order creation if email fails
    }

    // Send notification to admin
    try {
      await sendAdminNotificationNewOrder(order.id, customerName, customerEmail, botName, paymentMethod, transactionId)
    } catch (emailError) {
      console.error('Failed to send admin notification:', emailError)
      // Don't fail the order creation if email fails
    }

    return {
      success: true,
      orderId: order.id,
      status: order.status,
    }
  } catch (error) {
    console.error('Error creating order:', error)
    throw error
  }
}

export async function uploadPaymentProofFile(
  userId: string,
  orderId: string,
  file: File,
  customerEmail: string,
  customerName: string
) {
  try {
    // Validate file
    const validTypes = ['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'application/pdf']
    if (!validTypes.includes(file.type)) {
      throw new Error('Invalid file type. Only images and PDF are allowed.')
    }

    if (file.size > 10 * 1024 * 1024) {
      // 10MB limit
      throw new Error('File too large. Maximum size is 10MB.')
    }

    if (!orderId) {
      throw new Error('No order id was supplied, so the payment proof cannot be attached.')
    }

    // Upload file to the private payment-proofs bucket.
    // uploadPaymentProof returns the file PATH (bucket is PRIVATE) and now
    // THROWS with the real Supabase Storage message instead of returning null.
    const proofPath = await uploadPaymentProof(userId, orderId, file)

    // Update order with proof file path.
    // Admins access it via signed URLs generated by the API routes.
    const result = await (supabaseServer as any)
      .from('orders')
      .update({ payment_proof_url: proofPath })
      .eq('id', orderId)
      .eq('user_id', userId)
      .select()

    if (result.error) {
      throw new Error(
        `The file uploaded to storage (${proofPath}), but saving its path to order ${orderId} failed: ${result.error.message}`
      )
    }

    // `.update()` reports no error when it matches zero rows, which would have
    // left the proof orphaned in storage while the order kept no reference.
    if (!result.data || result.data.length === 0) {
      throw new Error(
        `The file uploaded to storage (${proofPath}), but order ${orderId} was not updated - no matching order for this user. The proof is not attached.`
      )
    }

    // Send payment submitted email
    try {
      const orderData = await (supabaseServer as any)
        .from('orders')
        .select('bot_name')
        .eq('id', orderId)
        .single()

      if (!orderData.error && orderData.data) {
        await sendPaymentSubmittedEmail(customerEmail, customerName, orderId, orderData.data.bot_name)
      }
    } catch (emailError) {
      console.error('Failed to send payment submitted email:', emailError)
    }

    return {
      success: true,
      proofPath,
      orderId,
    }
  } catch (error) {
    console.error('Error uploading payment proof:', error)
    throw error
  }
}

export async function getUserOrders(userId: string) {
  try {
    const { data, error } = await supabaseServer
      .from('orders')
      .select('*')
      .eq('user_id', userId)
      .order('created_at', { ascending: false })

    if (error) {
      throw error
    }

    return {
      success: true,
      orders: data,
    }
  } catch (error) {
    console.error('Error getting user orders:', error)
    throw error
  }
}

export async function getOrderById(orderId: string, userId: string) {
  try {
    const { data, error } = await supabaseServer
      .from('orders')
      .select('*')
      .eq('id', orderId)
      .eq('user_id', userId)
      .single()

    if (error) {
      throw error
    }

    return {
      success: true,
      order: data,
    }
  } catch (error) {
    console.error('Error getting order:', error)
    throw error
  }
}
