'use server'

import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'
import { supabaseServer, createOrder, updateOrderStatus } from '@/lib/supabase/server'
import { uploadPaymentProof } from '@/lib/supabase/server'
import {
  sendOrderConfirmationEmail,
  sendPaymentSubmittedEmail,
  sendAdminNotificationNewOrder,
} from '@/lib/email'

export async function createNewOrder(
  userId: string,
  botId: string,
  botName: string,
  botPrice: number,
  paymentMethod: string,
  transactionId: string,
  customerEmail: string,
  customerName: string
) {
  try {
    // Create order in database
    const orderData = await createOrder(
      userId,
      botId,
      botName,
      botPrice,
      paymentMethod,
      transactionId
    )

    if (!orderData || orderData.length === 0) {
      throw new Error('Failed to create order')
    }

    const order = orderData[0]

    // Send confirmation email to customer
    try {
      await sendOrderConfirmationEmail(customerEmail, customerName, order.id, botName, botPrice, paymentMethod)
    } catch (emailError) {
      console.error('Failed to send order confirmation email:', emailError)
      // Don't fail the order creation if email fails
    }

    // Send notification to admin
    try {
      await sendAdminNotificationNewOrder(order.id, customerName, customerEmail, botName, paymentMethod, transactionId)
    } catch (emailError) {
      console.error('Failed to send admin notification:', emailError)
      // Don't fail the order creation if email fails
    }

    return {
      success: true,
      orderId: order.id,
      status: order.status,
    }
  } catch (error) {
    console.error('Error creating order:', error)
    throw error
  }
}

export async function uploadPaymentProofFile(
  userId: string,
  orderId: string,
  file: File,
  customerEmail: string,
  customerName: string
) {
  try {
    // Validate file
    const validTypes = ['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'application/pdf']
    if (!validTypes.includes(file.type)) {
      throw new Error('Invalid file type. Only images and PDF are allowed.')
    }

    if (file.size > 10 * 1024 * 1024) {
      // 10MB limit
      throw new Error('File too large. Maximum size is 10MB.')
    }

    // Upload file to private payment-proofs bucket
    // uploadPaymentProof returns the file PATH (not a public URL - bucket is PRIVATE)
    const proofPath = await uploadPaymentProof(userId, orderId, file)

    if (!proofPath) {
      throw new Error('Failed to upload payment proof')
    }

    // Update order with proof file path
    // Admins will access via signed URLs generated by API endpoints
    const result = await (supabaseServer as any)
      .from('orders')
      .update({ payment_proof_url: proofPath })
      .eq('id', orderId)
      .eq('user_id', userId)
      .select()

    if (result.error) {
      throw result.error
    }

    // Send payment submitted email
    try {
      const orderData = await (supabaseServer as any)
        .from('orders')
        .select('bot_name')
        .eq('id', orderId)
        .single()

      if (!orderData.error && orderData.data) {
        await sendPaymentSubmittedEmail(customerEmail, customerName, orderId, orderData.data.bot_name)
      }
    } catch (emailError) {
      console.error('Failed to send payment submitted email:', emailError)
    }

    return {
      success: true,
      proofPath: proofPath,
    }
  } catch (error) {
    console.error('Error uploading payment proof:', error)
    throw error
  }
}

export async function getUserOrders(userId: string) {
  try {
    const { data, error } = await supabaseServer
      .from('orders')
      .select('*')
      .eq('user_id', userId)
      .order('created_at', { ascending: false })

    if (error) {
      throw error
    }

    return {
      success: true,
      orders: data,
    }
  } catch (error) {
    console.error('Error getting user orders:', error)
    throw error
  }
}

export async function getOrderById(orderId: string, userId: string) {
  try {
    const { data, error } = await supabaseServer
      .from('orders')
      .select('*')
      .eq('id', orderId)
      .eq('user_id', userId)
      .single()

    if (error) {
      throw error
    }

    return {
      success: true,
      order: data,
    }
  } catch (error) {
    console.error('Error getting order:', error)
    throw error
  }
}
